config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/course_intro', to: 'static_pages#course_intro'
  get    '/teachers',     to: 'static_pages#teachers'
  get    '/students',     to: 'static_pages#students'
  get    '/faq',          to: 'static_pages#faq'
  get    '/contact',      to: 'static_pages#contact'
  get    '/signup',       to: 'users#new'
  get    '/login',        to: 'sessions#new'
  post   '/login',        to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'

  # admin
  # account
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # camp
  resources :works, only: [:show]
  resources :posts, only: [:show]
  resources :camps, only: [:show] do
    resources :courses, only: [:index, :show]
    resources :meetup_groups, only: [:index, :show, :new]
    resources :live_broadcasts, only: [:index]
    resources :competitions, only: [:index, :show]
    resources :conversations, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camp.rb
class Camp < ApplicationRecord
  has_many :user_campships
  has_many :users, through: :user_campships
  has_many :courses
  has_many :competitions
  has_many :live_broadcasts
  has_many :conversations
  has_many :meetup_groups
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :camp
  has_many :works
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :camp
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :camp
  has_many :syllabuses
end

app/models/live_broadcast.rb
class LiveBroadcast < ApplicationRecord
  belongs_to :camp
end

app/models/meetup_group.rb
class MeetupGroup < ApplicationRecord
  belongs_to :camp
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :syllabus
  has_many :tasks
end

app/models/signin_log.rb
class SigninLog < ApplicationRecord
  belongs_to :user
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  belongs_to :course
  has_many :posts
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :user_campships
  has_many :camps, through: :user_campships
  has_many :signin_logs

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
             BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/models/user_campship.rb
class UserCampship < ApplicationRecord
  belongs_to :user
  belongs_to :camp
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :competition
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def course_intro
  end

  def teachers
  end

  def students
  end

  def faq
  end

  def contact
  end
end

app/helpers/camps_helper.rb
module CampsHelper
  def current_camp
    @current_camp ||= find_camp
  end

  def find_camp
    if (camp_id = params[:camp_id])
      session[:camp_id] = camp_id
      Camp.find_by(id: camp_id)
    elsif camp_id.blank? && session[:camp_id]
      Camp.find_by(id: session[:camp_id])
    else
      Camp.first
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/static_pages/contact.html.erb
<%= provide(:title, "联系方式") %>
<h2>联系方式</h2>
<%= link_to "jiujiubad@gmail.com", "#" %>
<%= link_to "在线客服", "#" %>

app/views/static_pages/course_intro.html.erb
<%= provide(:title, "课程介绍") %>
<h2>Python 入门之路</h2>
3周
课前作业辅导
3周
初级项目实战
5周
中级项目实战
3周
职业课（选修）

<%= link_to "开始学习!", signup_path, class: "btn btn-lg btn-primary" %>

第一阶段  Python基础
可掌握的核心能力1、掌握Python基础语法，具备基础的编程能力；
2、建立起编程思维以及面向对象程序设计思想。
解决的现实问题：能够熟练使用Python技术完成针对小问题的程序编写。

第二阶段  Web基础开发
1、能够熟练使用Linux操作系统；
2、掌握网络编程相关技术，能够实现网络间数据通信；
3、掌握程序设计开发中多任务实现方式；
4、能够熟练掌握MySQL操作相关技术，熟练编写各种数据库操作SQL语句，并能够进行Python与MySQL之间的数据交互；
5、掌握Python中的re模块的使用，能够实现对字符串进行复杂模式匹配；
6、掌握Web服务器的工作流程，以及Web框架的实现原理。
解决的现实问题：能够使用面向对象的程序设计方法, 基于Linux操作系统开发多任务的网络程序开发。

第三阶段   Web-Django框架与项目
可掌握的核心能力1、掌握Python Web主流框架-Django的使用；
2、可根据Web框架设计，开发对应的数据库；
3、可根据业务流程图，开发Web网站的前后台业务。
解决的现实问题：
1、能够开发主流Web网站，并掌握常见的技术要点；
2、根据实际问题设计出相应数据库表。

第四阶段  Web-Flask框架与项目
1、掌握Python Web主流框架-Flask的使用；
2、掌握常见的性能优化技术；
3、缓存服务器的操作和设计；
4、异步任务的实现。
解决的现实问题：
1、高并发全功能的Web网站开发；
2、提升数据处理响应速度，灵活运用缓存。

第五阶段  人工智能机器学习编程
1、掌握数据挖掘基础工具使用；
2、掌握机器学习中处理数据方法；
3、理解常见机器学习算法原理。
解决的现实问题：
1、利用学习到的科学计算库对收集到的数据进行数据基本处理，使其符合机器学习算法模型；
2、利用学习到的机器学习算法解决部分实际问题。

第六阶段  人工智能机器学习编程
1、掌握推荐系统的工作原理和实现流程；
2、掌握推荐系统的算法实现原理以及应用场景；
3、掌握Lambda大数据相关基础；
4、可实现基于大数据框架的推荐系统搭建；
5、能够基于推荐业务流完成系统搭建。
解决的现实问题：
1、能够实现推荐系统的算法不同场景应用；
2、能够根据推荐场景业务流完成推荐业务开发。

<%= link_to "开始学习!", signup_path, class: "btn btn-lg btn-primary" %>

app/views/static_pages/faq.html.erb
<%= provide(:title, "常见问题") %>
<h3>常见问题</h3>

<h3>如何购买 VIP ？</h3>
首页点击开始学习按钮，微信或支付宝扫码付费，付费后两小时内会有老师联系您，帮您开通付费课程。

<h3>学习这门课需要哪些基础？</h3>
我们本以为，具备以下背景的人会学得快许多（至少其一）：

<li>较好的英文水平</li>
<li>自己捣鼓过 HTML / CSS / JavaScript
<li>至少使用过一门编程语言（有基本能力即可）</li>
<li>良好的中文写作能力</li>
然而通过对线下课和线上课学员的观察，我们发现，90%的同学都是英文一般、编程零基础、没有中文写作能力，他们却一样能学得很好。

<h3>请问这个课需要怎么样的英文水平？</h3>
客观的说，编程世界常用的英文单词，只有200多个，所以，我们并不要求你是英文大牛。
同时，如果你具备以下程度，学习会顺利不少;如果不具备，在我们的学习过程中也可以慢慢培养出来：
<li>习惯使用 Google 查找资料，并能辨认找到的资讯是否有价值</li>
<li>可以快速地略读英文材料</li>

<h3>需要全职学习吗？</h3>
本课程为线上进行，你可以自行安排适合的学习时间，建议每天花 2 个小时进行学习。

<h3>需要准备什么东西？</h3>
一个外接屏幕（尺寸越大越好，在看代码的时候会方便很多）
一把好的机械式键盘（提高输入效率）
一个“可以接触墙外世界的网络帐号”（你懂的...）
好的网速（据学员反映，初学编程最大的挫折是下载安装环境太慢...）
Gmail 帐号

app/views/static_pages/home.html.erb
<div class="welcome-box">
  <!--===== 大图 =====-->
  <header id="header">
    <div class="header-wrapper-inner">
      <div class="container">

        <div class="welcome-speech">
          <h1>暴力入门，成为下一个想要的自己</h1>
          <p>Python 入门课，现已开放报名</p>
          <%= link_to('开始学习!', signup_path, class:'btn btn-push') %>
        </div>

      </div>
    </div>
  </header>

  <!--===== 服务优势 =====-->
  <section class="service-box">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h2>服务优势</h2> <!-- 副标题 -->
        <div class="short-line"></div> <!-- 分隔线 -->
        <div class="row">
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="box">
              <%= image_tag("jimi/service_1.png") %> <!-- 图示 -->
              <h3>品质保证</h3> <!-- 标题 -->
              <p>本店的商品皆通过市场验证，使用最高级的材料制作而成，品质为业界领先标准。</p> <!-- 内文 -->
            </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="box">
              <%= image_tag("jimi/service_2.png") %>
              <h3>快速送达</h3>
              <p>全国皆享有当天下单、隔日送达的服务，过程中有任何损坏皆由我们负责，请放心购买。</p>
            </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="box">
              <%= image_tag("jimi/service_3.png") %>
              <h3>安心使用</h3>
              <p>设计皆考量人体工学及真实使用情境，使用起来更安心。</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!--===== 推荐商品 =====-->
  <section class="show-box">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h2>推荐商品</h2> <!-- 副标题 -->
        <div class="short-line"></div> <!-- 分隔线 -->
        <div class="row">
          <div class="col-md-3">
            <%= link_to '#' do %> <!-- 商品连结 -->
              <div class="box"><%= image_tag("home/java.jpg") %></div> <!-- 商品图片 -->
              <div class="content">
                <p>两手锅</p> <!-- 商品名称 -->
                <p>$550</p> <!-- 商品价格 -->
              </div>
            <% end %>
          </div>
          <div class="col-md-3">
            <%= link_to '#' do %>
              <div class="box"><%= image_tag("home/python.jpg") %></div>
              <div class="content">
                <p>平底锅</p>
                <p>$750</p>
              </div>
            <% end %>
          </div>
          <div class="col-md-3">
            <%= link_to '#' do %>
              <div class="box"><%= image_tag("home/javascript.jpg") %></div>
              <div class="content">
                <p>铁制茶壶</p>
                <p>$450</p>
              </div>
            <% end %>
          </div>
          <div class="col-md-3">
            <%= link_to '#' do %>
              <div class="box"><%= image_tag("home/java.jpg") %></div>
              <div class="content">
                <p>茶壶</p>
                <p>$250</p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!--===== 用户反馈 =====-->
  <section class="feedback-box">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2>用户反馈</h2> <!-- 副标题 -->
        <div class="short-line"></div> <!-- 分隔线 -->
        <div id="feedback" class="carousel slide" data-ride="carousel">
          <!--===== 轮播按钮 =====-->
          <ol class="carousel-indicators">
            <li data-target="#feedback" data-slide-to="0" class="active"></li>
            <li data-target="#feedback" data-slide-to="1"></li>
            <li data-target="#feedback" data-slide-to="2"></li>
          </ol>

          <!--===== 轮播内容 =====-->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <p>这是我用过最好的网站，商品众多、下单方便、送货快速，还能订制特殊规格的锅具，强力推荐。</p>
              <%= image_tag("avatar/a4.png") %> <!-- 图片 -->
              <strong>Eddie - 上班族</strong> <!-- 介绍 -->
            </div>
            <div class="item">
              <p>我是这网站的忠实用户，已经在这买好几年了，质量一直很好，而且不定时会有折扣，真的很划算！</p>
              <%= image_tag("avatar/a1.png") %>
              <strong>Anna - 家庭主妇</strong>
            </div>
            <div class="item">
              <p>身为一个学生，预算不太多，却也能在这找到便宜又有设计感的器皿，让我生活又添加一份乐趣。</p>
              <%= image_tag("avatar/a6.png") %>
              <strong>Kobe - 大学生</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!--===== 合作品牌 =====-->
  <section class="brand-box bg-gray-light">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h2>合作品牌</h2>
        <div class="short-line"></div>
        <%= image_tag("jimi/brand_1.png") %>
        <%= image_tag("jimi/brand_2.png") %>
        <%= image_tag("jimi/brand_3.png") %>
        <%= image_tag("jimi/brand_4.png") %>
        <%= image_tag("jimi/brand_5.png") %>
        <%= image_tag("jimi/brand_6.png") %>
        <%= image_tag("jimi/brand_7.png") %>
        <%= image_tag("jimi/brand_8.png") %>
        <%= image_tag("jimi/brand_9.png") %>
      </div>
    </div>
  </section>

  <!--===== 立即购买 =====-->
  <section class="push-box">
    <%= link_to('开始学习!', '#', class:'btn btn-push') %>
  </section>
</div>

app/views/static_pages/students.html.erb
<%= provide(:title, "学员心得") %>
<h3>学员心得 | 学员作品</h3>

第一期线上班

<h3>学员推荐语</h3>
我之前在大学学过编程，毕业后也学过一点，但每次学习都会让我觉得编程晦涩难懂，参加有学才发现原来是学习的 方法不对。应该要先学习学习的方法，再去学习，仅仅这一点就为我打开了一扇新的大门，如果没有遇到有学也许以后也很难有机会明白这一点。更何况，有学帮我克服了编程恐惧症！ - wangyan66
这次的上课方式和以前我接触的很多线上课程都不一样，很多其他课程只是单纯教你技能，而不是教你做人，眼光不够长远，只是单纯迎合市场。这次的学习其实最大的感慨还是分享和帮助——这些软技能的应用。短短两三个月的学习，收获很大，改变很多。感谢老师们！- 小璐
来有学前，我没有任何基础，也不敢相信我可以学会编程，甚至是在这么短的时间内，可是来到有学后，我真的做到这一切了。 - Meely
有学的学习不仅仅是编程，在这里会让你学会分享与交流，让你学会学习，让你学会提升认知系统，让你学会项目管理，让你学会做产品并且会推广产品，让你个人能力飞速般的成长......有许多许多的可能。- 李小成
两个月来，自己真的感觉成长了许多，这不是能用金钱来衡量的。 1.课程设计合理。 2.老师非常牛。 3.效果非常好。 4.学生也非常牛。 5.是一次破茧重生之旅。 - 王小清
从来没有体会过用正确的学习方法极速学习的感觉。 体验过之后人生的学习效率极大的提高，相当于间接性地延长了寿命，这种好事怎么能不分享 - 宋小豪

<h3>学员作品</h3>
这是有学第一期线上班第一个月的成果 （数百个单人独立作品）
这是有学第一期线上班第二个月的成果（近百组双人远程协作）

第二期线上班

<h3>学员推荐语</h3>
有学的学习不仅仅是编程，在这里会让你学会分享与交流，让你学会学习，让你学会提升认知系统，让你学会项目管理，让你学会做产品并且会推广产品，让你个人能力飞速般的成长......有许多许多的可能。- 李小成
从来没有体会过用正确的学习方法极速学习的感觉。 体验过之后人生的学习效率极大的提高，相当于间接性地延长了寿命，这种好事怎么能不分享 - 宋小豪
两个月来，自己真的感觉成长了许多，这不是能用金钱来衡量的。 1.课程设计合理。 2.老师非常牛。 3.效果非常好。 4.学生也非常牛。 5.是一次破茧重生之旅。 - 王小清
来有学前，我没有任何基础，也不敢相信我可以学会编程，甚至是在这么短的时间内，可是来到有学后，我真的做到这一切了。 - Meely

<h3>学员作品</h3>
这是有学第一期线上班第一个月的成果 （数百个单人独立作品）
这是有学第一期线上班第二个月的成果（近百组双人远程协作）

第一期线下班

<h3>学员作品</h3>

<h3>学习方法</h3>
所有的编程学习过程其实都有套路可循，既没有想象的那么困难，也没有想象的那么简单。在7月初的时候，我们甚至连 Python 是什么都不懂，而到了现在，大家能自己做功能、自己 Debug，甚至开始团队合作开发项目。

那我作为一个初学者，我就有了两种方法来学 Python 啊。一种是像人类研究自然一样，观察，观察，连接输入和输出的规律，有了积累之后再去找个理论揣测黑箱的模式；或者，直接了解黑箱，了解完了黑箱，自然能够判断输入和输出的规律。现在老师在带着我们做的事情呢，就是对一个复杂的人工系统做类似于科学观察的黑箱探索。
<%= link_to "查看原文", "#" %>
我已经爱上了这种学习模式，如果你让我拿着 Python 基础教程这本书一直看，看到现在，我估计还是啥都做不出来，而这种学习模式让我现在有 10000% 的信心自己可以学好 Python 甚至更多的东西。
<%= link_to "查看原文", "#" %>
课程进行到现在，最大的收获应该是学习方法上的，因为这是可以举一反三的东西。用一个字来概括就是“用”，在知道了最少必要知识之后就去实战，然后在实战中再不断补充需要的知识，狠有成效。
<%= link_to "查看原文", "#" %>

<h3>团队合作</h3>
由于每个人负责的模块不同，虽然我不能亲自实现某个模块的某个功能，但代码在团队内是公开的，我们可以互相学习其他队员写的好的地方，有学老师的代码批改也会让我们学习到某些编码方式的最佳实践。所以团队合作也是一种“学习方式”。
<%= link_to "查看原文", "#" %>
我发现在一个良好的协作氛围中，可以更快速地学到很多东西。开会讨论问题的时候，队友们的思路都很广。以前只是作为用户去用一些产品，现在要从开发者的角度来思考问题，所以要多多向他们学习。
<%= link_to "查看原文", "#" %>

app/views/static_pages/teachers.html.erb
<%= provide(:title, "教学团队") %>
<h2>教学团队</h2>

张小学
<hr/>
<h2>知名 Python 教练，Python 吉尼斯奖得主</h2>
有学／Leading 创始人
Python／敏捷开发／Growthhack 专家及讲师

著作：
《Python 实战测试技术》
《Python 入门三十讲》

专栏：
《Pythone 每日十五分》


林小学
<h2>Python / Vue 大神</h2>
PythonGame 创始人
PythonConf Shanghai 创办人
多次 PythonConf 大会讲者

著作：
《leanr python as a game》