config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/course_intro', to: 'static_pages#course_intro'
  get    '/teachers',     to: 'static_pages#teachers'
  get    '/students',     to: 'static_pages#students'
  get    '/faq',          to: 'static_pages#faq'
  get    '/contact',      to: 'static_pages#contact'
  get    '/signup',       to: 'users#new'
  get    '/login',        to: 'sessions#new'
  post   '/login',        to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'

  # admin
  # account
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # camp
  resources :works, only: [:show]
  resources :posts, only: [:show]
  resources :camps, only: [:show] do
    resources :courses, only: [:index, :show]
    resources :meetup_groups, only: [:index, :show, :new]
    resources :live_broadcasts, only: [:index]
    resources :competitions, only: [:index, :show]
    resources :conversations, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camp.rb
class Camp < ApplicationRecord
  has_many :user_campships
  has_many :users, through: :user_campships
  has_many :courses
  has_many :competitions
  has_many :live_broadcasts
  has_many :conversations
  has_many :meetup_groups
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :camp
  has_many :works
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :camp
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :camp
  has_many :syllabuses
end

app/models/live_broadcast.rb
class LiveBroadcast < ApplicationRecord
  belongs_to :camp
end

app/models/meetup_group.rb
class MeetupGroup < ApplicationRecord
  belongs_to :camp
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :syllabus
  has_many :tasks
end

app/models/signin_log.rb
class SigninLog < ApplicationRecord
  belongs_to :user
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  belongs_to :course
  has_many :posts
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :user_campships
  has_many :camps, through: :user_campships
  has_many :signin_logs

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
             BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/models/user_campship.rb
class UserCampship < ApplicationRecord
  belongs_to :user
  belongs_to :camp
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :competition
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  def index
    @competitions = current_camp.competitions
  end

  def show
    @competition = Competition.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "有学"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  # Markdown 语法高亮：Coderay
  class HTMLwithCodeRay < Redcarpet::Render::HTML
    def block_code(code, language)
      if language
        <<-EOS
        <div class="code_block"> 
          <div class="code_header"> 
            #{CGI.escapeHTML(language.to_s)}  
          </div> 
          #{CodeRay.scan(code, language ||= :text).div(tab_width: 2, line_numbers: :inline)}  
        </div>
        EOS
      else
        CodeRay.scan(code, language ||= :text).div(tab_width: 2, line_numbers: :inline)
      end
    end
  end

  # Markdown to Html 解析：Coderay
  def markdown(text)
    renderer = HTMLwithCodeRay.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

end

app/helpers/camps_helper.rb
module CampsHelper
  def current_camp
    @current_camp ||= find_camp
  end

  def find_camp
    if (camp_id = params[:camp_id])
      session[:camp_id] = camp_id
      Camp.find_by(id: camp_id)
    elsif camp_id.blank? && session[:camp_id]
      Camp.find_by(id: session[:camp_id])
    else
      Camp.first
    end
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/competitions/index.html.erb
<section class="bg-white">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>全部比赛</h1>
      <p>在这里，留下你的脚印</p>
      <div class="row">

        <% @competitions.each do |c| %>
          <div class="col-md-6">
            <div class="row">
              <%= link_to camp_competition_path(current_camp, c) do %>
                <div class="col-md-4">
                  <%= image_tag c.image, style: "width:200px" %>
                </div>
                <div class="col-md-8">
                  <%= c.name %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/competitions/show.html.erb
<header class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= link_to '我的作品' %>
        <%= link_to '查看往期比赛' %>
      </div>
    </div>
  </div>
</header>

<section class="works">
  <div class="container">

  </div>
</section>




<ul id="myTab" class="nav nav-tabs">
  <li class="active"><a href="#home" data-toggle="tab">
    作品首页</a></li>
  <li><a href="#ios" data-toggle="tab">最新作品</a></li>
  <li><a href="#ios" data-toggle="tab">热门投票</a></li>
  <li><a href="#ios" data-toggle="tab">推荐作品</a></li>
  <li><a href="#ios" data-toggle="tab">最新评论</a></li>
  <li><a href="#ios" data-toggle="tab">我支持的作品</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade in active" id="home">
    <h3>推荐作品</h3>
    <h3>作品一览</h3>
    <div class="row">
      <% @competition.works.each do |w| %>
        <div class="col-md-3" style="height: 250px">
          <%= link_to work_path(w) do %>
            <%= image_tag w.image_small %>
            <p><%= w.name  %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="ios">
    <p>22 是一个由苹果公司开发和发布的手机操作系统。最初是于 2007 年首次发布 iPhone、iPod Touch 和 Apple
      TV。iOS 派生自 OS X，它们共享 Darwin 基础。OS X 操作系统是用在苹果电脑上，iOS 是苹果的移动版本。</p>
  </div>
  <div class="tab-pane fade" id="ios">
    <p>33 是一个由苹果公司开发和发布的手机操作系统。最初是于 2007 年首次发布 iPhone、iPod Touch 和 Apple
      TV。iOS 派生自 OS X，它们共享 Darwin 基础。OS X 操作系统是用在苹果电脑上，iOS 是苹果的移动版本。</p>
  </div>
  <div class="tab-pane fade" id="ios">
    <p>44 是一个由苹果公司开发和发布的手机操作系统。最初是于 2007 年首次发布 iPhone、iPod Touch 和 Apple
      TV。iOS 派生自 OS X，它们共享 Darwin 基础。OS X 操作系统是用在苹果电脑上，iOS 是苹果的移动版本。</p>
  </div>
  <div class="tab-pane fade" id="ios">
    <p>55 是一个由苹果公司开发和发布的手机操作系统。最初是于 2007 年首次发布 iPhone、iPod Touch 和 Apple
      TV。iOS 派生自 OS X，它们共享 Darwin 基础。OS X 操作系统是用在苹果电脑上，iOS 是苹果的移动版本。</p>
  </div>
  <div class="tab-pane fade" id="ios">
    <p>66 是一个由苹果公司开发和发布的手机操作系统。最初是于 2007 年首次发布 iPhone、iPod Touch 和 Apple
      TV。iOS 派生自 OS X，它们共享 Darwin 基础。OS X 操作系统是用在苹果电脑上，iOS 是苹果的移动版本。</p>
  </div>
</div>

<script>
  $(function(){
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
      // 获取已激活的标签页的名称
      var activeTab = $(e.target).text();
      // 获取前一个激活的标签页的名称
      var previousTab = $(e.relatedTarget).text();
      $(".active-tab span").html(activeTab);
      $(".previous-tab span").html(previousTab);
    });
  });
</script>