config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/course_intro', to: 'static_pages#course_intro'
  get    '/teachers',     to: 'static_pages#teachers'
  get    '/students',     to: 'static_pages#students'
  get    '/faq',          to: 'static_pages#faq'
  get    '/contact',      to: 'static_pages#contact'
  get    '/signup',       to: 'users#new'
  get    '/login',        to: 'sessions#new'
  post   '/login',        to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'

  # admin
  # account
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # camp
  resources :works, only: [:show]
  resources :posts, only: [:show]
  resources :camps, only: [:show] do
    resources :courses, only: [:index, :show]
    resources :meetup_groups, only: [:index, :show, :new]
    resources :live_broadcasts, only: [:index]
    resources :competitions, only: [:index, :show]
    resources :conversations, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camp.rb
class Camp < ApplicationRecord
  has_many :user_campships
  has_many :users, through: :user_campships
  has_many :courses
  has_many :competitions
  has_many :live_broadcasts
  has_many :conversations
  has_many :meetup_groups
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :camp
  has_many :works
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :camp
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :camp
  has_many :syllabuses
end

app/models/live_broadcast.rb
class LiveBroadcast < ApplicationRecord
  belongs_to :camp
end

app/models/meetup_group.rb
class MeetupGroup < ApplicationRecord
  belongs_to :camp
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :syllabus
  has_many :tasks
end

app/models/signin_log.rb
class SigninLog < ApplicationRecord
  belongs_to :user
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  belongs_to :course
  has_many :posts
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :user_campships
  has_many :camps, through: :user_campships
  has_many :signin_logs

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
             BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/models/user_campship.rb
class UserCampship < ApplicationRecord
  belongs_to :user
  belongs_to :camp
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :competition
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = current_camp.courses
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "有学"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  # Markdown 语法高亮：Coderay
  class HTMLwithCodeRay < Redcarpet::Render::HTML
    def block_code(code, language)
      if language
        <<-EOS
        <div class="code_block"> 
          <div class="code_header"> 
            #{CGI.escapeHTML(language.to_s)}  
          </div> 
          #{CodeRay.scan(code, language ||= :text).div(tab_width: 2, line_numbers: :inline)}  
        </div>
        EOS
      else
        CodeRay.scan(code, language ||= :text).div(tab_width: 2, line_numbers: :inline)
      end
    end
  end

  # Markdown to Html 解析：Coderay
  def markdown(text)
    renderer = HTMLwithCodeRay.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

end

app/helpers/camps_helper.rb
module CampsHelper
  def current_camp
    @current_camp ||= find_camp
  end

  def find_camp
    if (camp_id = params[:camp_id])
      session[:camp_id] = camp_id
      Camp.find_by(id: camp_id)
    elsif camp_id.blank? && session[:camp_id]
      Camp.find_by(id: session[:camp_id])
    else
      Camp.first
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/courses/index.html.erb
<% provide(:page_id, "portfolio-page") %>

<section class="course-header">
  <div class="user-avatar">
    <%= image_tag current_user.avatar %>
  </div>
  <div class="vip-state">
    <%= image_tag "jimi/vip-member.png" %>
  </div>
  <p><%= link_to current_user.name %></p>
</section>

<section class="course-box">
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-12">
      <div class="row">

        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              最新通知
            </div>
            <div class="panel-body">
              同学们可以点击这里自行创建线上或者线下 Meetup，和更多小伙伴一起学习，共同成长。
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              同学说
            </div>
            <div class="panel-body">
              <p>【大赛复盘】商店魔改大赛复盘</p>
              <p>【大赛复盘】魔改大赛第二期：我们为什么要学习编程？</p>
              <p>【大赛复盘】大赛让我看到了颠覆的力量</p>
            </div>
          </div>
        </div>

      </div>
    </div>
    <div class="col-md-9 col-sm-9 col-xs-12">
      <div class="course-content">
        <div class="course-tab">
          <ul id="myTab" class="nav nav-tabs">
            <li class="active">
              <a href="#home" data-toggle="tab">
                菜鸟教程
              </a>
            </li>
            <li><a href="#ios" data-toggle="tab">iOS</a></li>
          </ul>
        </div>

        <div class="all-course">
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="home">
              <% @courses.each do |c| %>
                <div class="course-card-unlock">
                  <div class="course-img">
                    <%= image_tag(c.image) %>
                  </div>
                  <div class="title">
                    <h3><%= c.name %></h3>
                  </div>
                  <div class="title-cover"></div>
                  <div class="block">
                    <p class="time">预计学习时间： 7小时</p>
                    <div class="bar">
                      <div class="percent"></div>
                    </div>
                    <p class="task">共1个作业，已完成0个</p>
                  </div>
                  <a href="/camps/<%= current_camp.id %>/courses/<%= c.id %>">
                    <div class="start">
                      <button type="button" class="btn btn-blue">进入课程</button>
                    </div>
                  </a>
                </div>
              <% end %>
            </div>
            <div class="tab-pane fade" id="ios">
              <div class="row">
                <div class="col-md-11 col-center">

                  <% @courses.each do |c| %>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                      <div class="card-lock">
                        <div class="course-img">
                          <%= image_tag(c.image, class: "img-responsive") %>
                        </div>
                        <div class="title">
                          <h3><%= c.name %></h3>
                        </div>
                        <div class="title-cover"></div>
                        <div class="block">
                          <p class="time">预计学习时间： 7小时</p>
                          <div class="bar">
                            <div class="percent"></div>
                          </div>
                          <p class="task">共1个作业，已完成0个</p>
                        </div>
                        <a href="/camps/<%= current_camp.id %>/courses/<%= c.id %>">
                          <div class="start">
                            <button type="button" class="btn btn-blue">进入课程</button>
                          </div>
                        </a>
                      </div>
                    </div>
                  <% end %>

                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/courses/show.html.erb
<% provide(:page_id, "course-show-page") %>

<%= render 'shared/course_nav' %>

<section class="course-show">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="content">

        <div class="header">
          <h4>当前进度</h4>
          <p>总共2个作业，已完成2个。</p>
          <div class="bar">
            <div class="progress">
              <div class="percent">60%</div>
            </div>
          </div>
        </div>

        <div class="syllabus">
          <table class="table">
            <% @course.syllabuses.each do |s| %>
              <thead>
                <tr>
                  <th>
                    <h3><%= s.name %></h3>
                    <div class="far fa-clock">
                      预计学习时间: 2小时以内
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% s.posts.each do |p| %>
                  <tr>
                    <td>
                      <div class="post">
                        <i class="fa fa-circle"></i>
                        <%= link_to p.name, post_path(p) %>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            <% end %>
          </table>
        </div>

      </div>
    </div>
  </div>
</section>